### ISSUE TITLE
[Bug] Can't run examples using python 2.7

### ISSUE THREAD

**Issue by ayoubSoussi** [IDA-TUBS/pycpa#20]
I tried to run some basic examples provided in the repo using python 2.7, but I get errors in the execution of `start = time.process_time()` in `analysis.py` file.
This is what I get when I execute the spp_test.py example.
`python spp_test.py`
![bugg](https://user-images.githubusercontent.com/34512229/103345723-78f5fe00-4a92-11eb-9f57-2fe5a28a9045.png)

The examples work fine when I use python 3.6 in the same machine.
These are the details of my installation environment
`OS : UBUNTU 18.04 LTS`
`python --version : 2.7.17`
`python3 --version : 3.6.9`

**Comment by jschlatow** [comment]
@ayoubSoussi thank you for the bug report. It has been fixed in current master.
