### ISSUE TITLE
Add **register a periodic with jitter event model** step to the step by step example

### ISSUE THREAD

**Issue by bhomaidan1990** [IDA-TUBS/pycpa#21]
Can you please add the step of  the periodic jitter registration before the [System Analysis](https://pycpa.readthedocs.io/en/latest/spp_example.html#analysis) step in the documentation, in case someone was trying to go over the Example step by step, thanks in advance.
```py
    # register a periodic with jitter event model for T11 and T12
    t11.in_event_model = model.PJdEventModel(P=30, J=5)
    t12.in_event_model = model.PJdEventModel(P=15, J=6)
```

**Comment by bhomaidan1990** [comment]
sorry I didn't notice it

**Comment by bhomaidan1990** [comment]
It's mentioned in the latter documentation, but for the new readers who will try to test the code step by step, it will not work and they will be confused if they didn't continue to the next sections or the full code down.

**Comment by jschlatow** [comment]
@bhomaidan1990 Thank you for the suggestion and your explanation. We will add this step in the example for clarity.
